service:
  build: .
  ports:
    - "8888:8888"
  volumes:
    - ./home/ferbie/ai:/home/git/
  environment:
    FLASK_ENV: development
  command: flask run --host=0.0.0.0
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [ gpu ]
